package com.moneyhandler.util;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

import com.moneyhandler.model.TransactionModel;

import java.io.OutputStream;
import java.util.List;
import java.util.stream.Stream;

/**
 * Utility to generate and export combined transaction report as PDF.
 */
public class PDFExportUtil {

    public static void generateTransactionReportPDF(List<TransactionModel> transactions, OutputStream out) {
        Document document = new Document(PageSize.A4);
        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Title
            Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD, BaseColor.DARK_GRAY);
            Paragraph title = new Paragraph("MoneyHandler - Transaction Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20f);
            document.add(title);

            // Table
            PdfPTable table = new PdfPTable(4); // type, category, amount, date
            table.setWidthPercentage(100);
            table.setWidths(new int[]{2, 3, 2, 2});

            addTableHeader(table);
            addRows(table, transactions);

            document.add(table);

            // Footer
            Paragraph footer = new Paragraph("\nReport generated by MoneyHandler", new Font(Font.FontFamily.HELVETICA, 10, Font.ITALIC));
            footer.setAlignment(Element.ALIGN_RIGHT);
            document.add(footer);

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            document.close();
        }
    }

    private static void addTableHeader(PdfPTable table) {
        Font headFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD);
        Stream.of("Type", "Category", "Amount (Rs.)", "Date")
                .forEach(headerTitle -> {
                    PdfPCell header = new PdfPCell();
                    header.setBackgroundColor(new BaseColor(240, 240, 240));
                    header.setHorizontalAlignment(Element.ALIGN_CENTER);
                    header.setPhrase(new Phrase(headerTitle, headFont));
                    table.addCell(header);
                });
    }

    private static void addRows(PdfPTable table, List<TransactionModel> transactions) {
        for (TransactionModel tx : transactions) {
            table.addCell(tx.getType());
            table.addCell(tx.getCategory());
            table.addCell(String.format("Rs. %.2f", tx.getAmount()));
            table.addCell(tx.getDate().toString());
        }
    }
}
